#!/usr/bin/env python3
"""tf_export.py -- zip a generated theme, with a generated HOW-TO-USE.md.

Zips with zipfile so arcnames are controlled (everything lands under a folder
named for the slug). Refuses to overwrite without --force; suffixes instead.
Records the export in run.json. Works whether or not the theme was applied.

    python3 tf_export.py --theme <slug-or-number> [--out <dir>] --json [--force]
"""
from __future__ import annotations

import json
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

sys.dont_write_bytecode = True  # never leave __pycache__ inside the plugin dir
import tf_paths


def _now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_run(paths):
    if paths.run_json.is_file():
        try:
            return json.loads(paths.run_json.read_text(encoding="utf-8"))
        except Exception:
            return None
    return None


def resolve_theme(paths, run, key):
    """Resolve a slug or 1-based number to (slug, name, theme_dir)."""
    themes = (run or {}).get("themes", [])
    entry = None
    if key.isdigit():
        idx = int(key)
        for t in themes:
            if t.get("index") == idx:
                entry = t
                break
    if entry is None:
        for t in themes:
            if t.get("slug") == key:
                entry = t
                break
    if entry is not None:
        d = paths.current / entry["dir"] if not Path(entry["dir"]).is_absolute() else Path(entry["dir"])
        return entry.get("slug"), entry.get("name", entry.get("slug")), d

    # Fall back to scanning the themes directory directly.
    if paths.current_themes.is_dir():
        for child in sorted(paths.current_themes.iterdir()):
            if not child.is_dir():
                continue
            slug = child.name.split("-", 1)[1] if "-" in child.name else child.name
            if slug == key or child.name == key or (key.isdigit() and child.name.startswith(key.zfill(2))):
                return slug, slug, child
    return None, None, None


HOWTO = """# {name} -- how to use this theme

This zip contains a complete, cross-platform design theme generated by Theme
Forge. Tokens are platform-neutral (`tokens.json`, DTCG format) and resolved
twice: to CSS (`web/`) and to flat React Native values (`native/`).

```
{slug}/
├── theme.json            canonical record (both resolutions)
├── tokens.json           platform-neutral DTCG tokens
├── web/                  theme.css, tailwind.theme.css, shadcn.css
├── native/               theme.ts, useTheme.ts, tailwind.config.js, fonts.md, app-icons.md
├── brand/                logo / icon / favicon / adaptive / splash / pattern SVGs
├── a11y.json             WCAG 2.2 AA contrast report
├── native.json           React Native translation report
└── preview.html          standalone 3-surface preview
```

Open `preview.html` in any browser to see the theme; it works offline.

## Web

**Plain CSS.** Copy `web/theme.css` into your project and import it once at your
entry (e.g. `import './theme.css'`). It declares `:root` custom properties plus a
`.dark` / `prefers-color-scheme` block. Reference them as `var(--color-primary)`.

**Tailwind v4.** Copy `web/tailwind.theme.css`. Add `@import "./tailwind.theme.css";`
after `@import "tailwindcss";`. It is a v4 CSS-first `@theme` block and generates
both the CSS variables and the utilities (`bg-primary`, `rounded-lg`, ...).

**shadcn/ui.** Copy the `:root` and `.dark` variable blocks from `web/shadcn.css`
into your global stylesheet. They map to shadcn's semantic names
(`--background`, `--primary`, `--ring`, `--radius`, ...), so existing components
re-theme with zero edits.

## React Native

**Expo + NativeWind.** Merge `native/tailwind.config.js` (a Tailwind **v3**-shaped
config -- NOT the web v4 block) into your `tailwind.config.js`. Copy `native/theme.ts`
and `native/useTheme.ts` into your project. Wrap your root in a provider and read
values with `useTheme()`; it swaps light/dark from `useColorScheme()`.

**Expo + StyleSheet / bare React Native.** Use `native/theme.ts` + `native/useTheme.ts`
directly. All values are unitless numbers, resolved hex colors, absolute
lineHeights, and one registered family name per weight. See `native/fonts.md` for
the font packages to install and `native/app-icons.md` for the icon fields.

**Fonts.** React Native does not synthesize weights -- install the exact packages
in `native/fonts.md` and hold the splash screen until `useFonts` reports loaded.

**Dev build.** If `native.json` says `requires_dev_build: true`, this theme uses a
native module (e.g. `expo-blur`) that Expo Go cannot run. Build a development
client first.

## Monorepo (web app + native app)

Prefer writing the tokens **once** into a shared package (e.g. `packages/tokens`)
that exports the neutral token object plus both resolutions, then import the CSS
resolution in the web app and the native resolution in the mobile app.
Duplicating the theme into two apps guarantees drift. Regenerating then means
updating one package, not two apps.

## Rasterizing SVGs to PNGs

The Expo icon/splash fields are PNG-only. There is no guaranteed rasterizer; try
in order and use whichever exists (see `brand/RASTERIZE.md` for exact commands):

```
npx sharp-cli -i brand/icon.svg -o icon.png resize 1024 1024
rsvg-convert -w 1024 -h 1024 brand/icon.svg -o icon.png
magick -background none brand/icon.svg -resize 1024x1024 icon.png
inkscape brand/icon.svg --export-type=png --export-width=1024
```

## Accessibility

`a11y.json` records the WCAG 2.2 AA contrast check for every semantic pair in
both light and dark. Everything in it passed at generation time; re-run
`tf_contrast.py` if you change a color.
"""


def build_zip(theme_dir: Path, slug: str, name: str, out_zip: Path):
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(theme_dir.rglob("*")):
            if f.is_file():
                arc = "%s/%s" % (slug, f.relative_to(theme_dir).as_posix())
                zf.writestr(arc, f.read_bytes())
        zf.writestr("%s/HOW-TO-USE.md" % slug, HOWTO.format(name=name, slug=slug))


def unique_path(base: Path) -> Path:
    if not base.exists():
        return base
    stem, suffix = base.stem, base.suffix
    i = 1
    while True:
        cand = base.with_name("%s-%d%s" % (stem, i, suffix))
        if not cand.exists():
            return cand
        i += 1


def main(argv):
    want_json = "--json" in argv
    force = "--force" in argv
    if "--theme" not in argv:
        sys.stderr.write("usage: tf_export.py --theme <slug-or-number> [--out <dir>] --json\n")
        print(json.dumps({"ok": False, "error": "missing --theme"}))
        return 1
    key = argv[argv.index("--theme") + 1]
    out_dir = Path(argv[argv.index("--out") + 1]) if "--out" in argv else Path(".")
    out_dir = out_dir.resolve()

    paths = tf_paths.resolve(create=True)
    run = load_run(paths)
    slug, name, theme_dir = resolve_theme(paths, run, key)
    if not theme_dir or not theme_dir.is_dir():
        msg = "theme %r not found in %s" % (key, paths.current_themes)
        sys.stderr.write("tf_export: %s\n" % msg)
        print(json.dumps({"ok": False, "error": msg}))
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / ("%s-theme.zip" % slug)
    if target.exists() and not force:
        target = unique_path(target)

    build_zip(theme_dir, slug, name, target)

    # Record the export in run.json.
    if run is not None:
        run.setdefault("exported", []).append(
            {"slug": slug, "zip": str(target), "at": _now_iso()})
        try:
            paths.run_json.write_text(json.dumps(run, indent=2) + "\n", encoding="utf-8")
        except Exception:
            pass

    result = {"ok": True, "slug": slug, "zip": str(target),
              "size_bytes": target.stat().st_size, "theme_dir": str(theme_dir)}
    sys.stderr.write("tf_export: wrote %s (%d bytes)\n" % (target, result["size_bytes"]))
    if want_json:
        print(json.dumps(result))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except Exception as exc:  # pragma: no cover
        sys.stderr.write("tf_export: unexpected error: %s\n" % exc)
        print(json.dumps({"ok": False, "error": str(exc)}))
        sys.exit(2)
